### ISSUE TITLE
Configure enabled states and initial state

### ISSUE THREAD

**Issue by Wyrrrd** [synox/mark-as-done-extension#1]
At first, thanks for the great extension, it is usable and clean (and, unlike others, doesn't forget ;)

I have some ideas though...

---
### Clicks
I need two mouse clicks somewhere away from the page I am reading to mark a page as done. That is a minor annoyance.

What would help:
- Being able to change the default state applied when clicking on the extension button.
- The ability to disable states completely, iterating on above point.
- Being able to assign separate keyboard shortcuts to apply the states.
---
### Redirects
I need the extension on a page that did not fully migrate all page links to a new URL. The old links aren't being colored by this extension (obviously).

What would help:
- A manual list of URL aliases, coloring links with the old URL according to the states of the corresponding new URL.
---
(Happy to split the issue into multiple, if you need it that way. I will also probably dive into the code myself and send PRs if I find time and if you want some or all of these suggested features.)

**Comment by synox** [comment]
These are great suggestions. I will try to integrate these after #2 is done.

**Comment by synox** [comment]
@Wyrrrd are you able to test the extension locally? There are instructions in the readme.md. 
I just got it to work in the branch https://github.com/synox/mark-as-done-extension/tree/settings-state, but it needs some more testing before releasing it. I would highly appreciate your feedback if it works and about the UX.

**Comment by Wyrrrd** [comment]
Using it in developer mode, the turning off categories works for me as expected. If I only switch on "done", the page gets this state on extension symbol click, as expected.

Sadly now the icon stays gray, regardless of the state of the current page, and the inline link formatting is gone too.

Will play around with it some more and report later, might have to do with my setup.

(Browser Info: Brave 64-Bit Version 1.51.118 Chromium: 113.0.5672.126)

**Comment by Wyrrrd** [comment]
Oh and the settings turn up in the link list. Not sure if they should.

![image](https://github.com/synox/mark-as-done-extension/assets/11527443/02b4632a-3b8d-4fbf-a2c0-e8f1ba59993c)

**Comment by synox** [comment]
Thank you for testing! 
I might have broken a few things in the recent refactoring. I will fix these. 
So the flow is ok, once i fix the bugs? 

one thing i also want to address is that currently the icon is disabled on internal urls. Instead it should at least show a link to all links.
