### ISSUE TITLE
Multiple regressions

### ISSUE THREAD

**Issue by Wyrrrd** [synox/mark-as-done-extension#13]
After the latest update, the extension had several regressions that make it unusable right now:

1. The icon does not represent the saved state of the site anymore, there is always just the grey shield visible.
2. New states are not written
3. Import is not working (may be related to 2)

Browser: Brave 1.56.20 64-bit

**Comment by synox** [comment]
Oops, i will look into this!

**Comment by synox** [comment]
I fixed it in the main branch, and submitted for Chrome and Firefox store. It might take a while to update in the stores.

**Comment by synox** [comment]
@Wyrrrd please let me know if this fixes the issues.

**Comment by Wyrrrd** [comment]
Tested import, adding states to new pages, icon matches state.

Everything's fixed, thank you for the quick work :)
